version: "3.9"

services:
  mariadb_42:
    image: mariadb_42
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - wordpress-network
    restart: always

  wordpress_42:
    image: wordpress_42
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    environment:
      WORDPRESS_DB_HOST: mariadb_42:3306
      WORDPRESS_DB_USER: ${MARIADB_USER}
      WORDPRESS_DB_PASSWORD: ${MARIADB_PASSWORD}
      WORDPRESS_DB_NAME: ${MARIADB_DATABASE}
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - wordpress-network
    depends_on:
      - mariadb_42
    restart: always

  nginx_42:
    image: nginx_42
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
      - "8080:80"
    networks:
      - wordpress-network
    volumes:
      - wordpress-data:/var/www/html
    depends_on:
      - wordpress_42
    restart: always
  # redis:
  #   image: redis
  #   networks:
  #     - wordpress-network
  
volumes:
  mariadb-data:
  wordpress-data:


networks:
  wordpress-network:
    driver: bridge
  
# driver: local
# driver_opts:
#   type: none
#   device: /home/aghounam/data/wordpress
#   o: bind

