version: "3.9"

services:

# mariadb service :
  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - wordpress-network
    restart: always

# redis service :
  redis:
    container_name: redis
    image: redis
    build: 
      context: ./bonus/redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
    networks:
      - wordpress-network
    restart: always
    depends_on:
      - mariadb


# wordpress service :
  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: ${MARIADB_USER}
      WORDPRESS_DB_PASSWORD: ${MARIADB_PASSWORD}
      WORDPRESS_DB_NAME: ${MARIADB_DATABASE}
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - wordpress-network
    depends_on:
      - mariadb
    restart: always

# ftp service :
  ftp:
    container_name: ftp
    image: ftp
    build:
      context: ./bonus/ftp
      dockerfile: Dockerfile
    volumes:
      - wordpress-data:/var/www/html
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    networks:
      - wordpress-network
    restart: always
    depends_on:
      - mariadb
      - wordpress

# nginx service :
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
      - "8080:80"
    networks:
      - wordpress-network
    volumes:
      - wordpress-data:/var/www/html
    depends_on:
      - wordpress
    restart: always
  
  
volumes:
  mariadb-data:
  wordpress-data:


networks:
  wordpress-network:
    driver: bridge
  
# driver: local
# driver_opts:
#   type: none
#   device: /home/aghounam/data/wordpress
#   o: bind

